# Generated by Django 5.0.7 on 2024-08-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ent', '0004_events_alter_otpverification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
